### ISSUE TITLE
Unauthorized issue

### ISSUE THREAD

**Issue by djKooks** [spotify/spydra#23]
Hello.
I just started following up the build process. I setup the authorization, created buckets, and run with maven but it is causing error.

```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.spotify.data.spydra:spydra-parent:pom:0.3.4-20170726.094703-3 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/spotify/data/spydra/spydra-parent/0.3.4-SNAPSHOT/spydra-parent-0.3.4-20170726.094703-3.pom. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:311)
	... 27 more
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/spotify/data/spydra/spydra-parent/0.3.4-SNAPSHOT/spydra-parent-0.3.4-20170726.094703-3.pom. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:627)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:541)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:523)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:517)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:497)
	at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run(WagonTransporter.java:644)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.put(WagonTransporter.java:410)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:510)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 29 more
[ERROR] 
[ERROR] 
```
How can I figure out which point has caused error with this log?
Thanks.

**Comment by varjoranta** [comment]
I am assuming you don't have access to the snapshots repository on Maven central. Try taking a snapshot from a release version which don't have the SNAPSHOT in versions in pom.xml. E.g. git checkout v0.3.3

**Comment by djKooks** [comment]
@varjoranta Thanks. But I still have same issue after checkout to v0.3.5
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project spydra-parent: Failed to deploy artifacts: Could not transfer artifact com.spotify.data.spydra:spydra-parent:pom:0.3.5 from/to ossrh (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/spotify/data/spydra/spydra-parent/0.3.5/spydra-parent-0.3.5.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project spydra-parent: Failed to deploy artifacts: Could not transfer artifact com.spotify.data.spydra:spydra-parent:pom:0.3.5 from/to ossrh (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/spotify/data/spydra/spydra-parent/0.3.5/spydra-parent-0.3.5.pom. Return code is: 401, ReasonPhrase: Unauthorized.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Do I have to setup something more?

**Comment by steffengr** [comment]
@djKooks How are you invoking maven and from what folder? I don't see why it should upload or download that pom in your case.

**Comment by steffengr** [comment]
I just spun up a vm and successfully build it by running ```mvn clean package -DskipTests -DskipITs -Dtest-configuration-dir=foo -Dinit-action-uri=bar``` in the repos main folder. Can you try and confirm that that works?

**Comment by djKooks** [comment]
@steffengr Running with command you commented works well. Could you find out what is wrong on me?

**Comment by varjoranta** [comment]
@djKooks Could you please copy/paste here the command you were using to run it when you got the error?

**Comment by varjoranta** [comment]
I found few issues in the build flow while trying out with fresh VM and fresh non-service-account user credentials. I will add fixes to these issues within couple of days, and let's try again afterwards.

Also running maven deploy won't work with the current repositories setup in pom.xml, unless you have Spotify access credentials setup for the artifactory in use, but the maven verify part should work. I will get back to you in couple of days.

**Comment by djKooks** [comment]
@varjoranta Oh thanks for followup! Please share me after done.

**Comment by varjoranta** [comment]
@djKooks I believe that you should just not run the maven "deploy" step but "install". I will make a change to put the init action uploads to happen on install step, in case you define profile when building, like -P release.

Otherwise some of the problems with non-service-account credentials is going to be fixed with PR https://github.com/spotify/spydra/pull/26

**Comment by varjoranta** [comment]
@djKooks The PR is now merged. Can you try again if you have any issues building, if you follow the instructions in README? Remember not to call mvn deploy, but mvn install.

**Comment by varjoranta** [comment]
Please re-open this issue if needed.

**Comment by djKooks** [comment]
@varjoranta Thanks! I'll let you know after retry.

**Comment by djKooks** [comment]
@varjoranta Sorry for late check.
I just check again, and find out some problem(this seems it's not a problem of project, but in my setting).
```
$ mvn clean install -Dinit-action-uri=gs://init-action-bucket/spydra -Dtest-configuration-dir=/path/to/config
...
 INFO [main] (LoggingMetrics.java:55) - Fatal error was caughtnull
DEBUG [main] (ProcessHelper.java:33) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com dataproc clusters delete spydra-73bea89f-0563-40a2-999d-6b4c85822771 --async --quiet --region=ASIA-EAST1 --project=gc-spydra-test
ERROR: (gcloud.dataproc.clusters.delete) Your current active account [spydra-test@gc-spydra-test.iam.gserviceaccount.com] does not have any valid credentials
```
It seems there are problem in my auth settings, but I couldn't find out.

```
$ gcloud init
Welcome! This command will take you through the configuration of gcloud.

Settings from your current configuration [default] are:
core:
  account: inylove82@gmail.com
  disable_usage_reporting: 'False'
  project: gc-spydra-test
```

This is my integration test config file.
```
{
  "log_bucket": "gcs-log-bucket ",
  "region": "ASIA-EAST1"
}
```

I also setup GOOGLE_APPLICATION_CREDENTIALS for project, too.
Could you find out what am I missing? Thanks.

**Comment by djKooks** [comment]
@varjoranta Could you figure out something?

**Comment by krisss85** [comment]
@djKooks Have you tried running _gcloud auth activate-service-account --key-file=path_to_json.json_ first?

**Comment by djKooks** [comment]
@krisss85 Thanks for help.
I tried again with key file received here(https://console.cloud.google.com/apis/credentials/serviceaccountkey), but it shows auth error like this.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.spotify.spydra.LifecycleIT
DEBUG [main] (SpydraArgumentUtil.java:70) - Merge conf found from classpath: defaults.json
DEBUG [main] (SpydraArgumentUtil.java:70) - Merge conf found from classpath: dataproc_defaults.json
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.671 sec <<< FAILURE! - in com.spotify.spydra.LifecycleIT
testLifecycle(com.spotify.spydra.LifecycleIT)  Time elapsed: 0.492 sec  <<< ERROR!
java.lang.IllegalArgumentException: GOOGLE_APPLICATION_CREDENTIALS needs to be set and point to a valid credential json
	at com.spotify.spydra.util.GcpUtils.credentialJsonFromEnv(GcpUtils.java:63)
	at com.spotify.spydra.util.GcpUtils.userIdFromJsonCredentialInEnv(GcpUtils.java:88)
	at com.spotify.spydra.util.SpydraArgumentUtil.dataprocConfiguration(SpydraArgumentUtil.java:115)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:69)


Results :

Tests in error: 
  LifecycleIT.testLifecycle:69 » IllegalArgument GOOGLE_APPLICATION_CREDENTIALS ...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```
Seems I'm doing something wrong, but couldn't figure out.
Could you figure out anything? Thanks.

**Comment by krisss85** [comment]
almost there just set env variable env GOOGLE_APPLICATION_CREDENTIALS=/path/to/key/my-gcp-credentials-key.json

see RELEASING.md

**Comment by djKooks** [comment]
@krisss85 Oh I missed that part, thanks.
But I faced on other problem like this.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.spotify.spydra.LifecycleIT
DEBUG [main] (SpydraArgumentUtil.java:70) - Merge conf found from classpath: defaults.json
DEBUG [main] (SpydraArgumentUtil.java:70) - Merge conf found from classpath: dataproc_defaults.json
DEBUG [main] (CompiledPath.java:47) - Evaluating path: $['client_email']
DEBUG [main] (CompiledPath.java:47) - Evaluating path: $['project_id']
DEBUG [main] (LifecycleIT.java:82) - Using following service account to run gcloud commands locally: spydra-test@gc-spydra-test.iam.gserviceaccount.com
 INFO [main] (MetricsFactory.java:38) - MetricsFactory was not initialized. Using default implementation.
DEBUG [main] (ProcessHelper.java:50) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com --format=json dataproc clusters create spydra-19ebe301-f34e-4026-8aec-939f069265bd --quiet --metadata=heartbeat=2017-11-09T00:35:03.244000Z,collector-timeout=30 --project=gc-spydra-test --scopes=cloud-platform --num-workers=3 --region=ASIA-EAST1 --service-account=spydra-test@gc-spydra-test.iam.gserviceaccount.com --properties=mapred:mapreduce.jobhistory.done-dir=gs://gcs-log-bucket /history/735ddd54-4920-46aa-9346-cbdea128ac83/done,mapred:mapreduce.jobhistory.intermediate-done-dir=gs://gcs-log-bucket /history/735ddd54-4920-46aa-9346-cbdea128ac83/e692fe05-e514-4614-942e-f80ce5b1fcf0/done_intermediate,mapred:mapreduce.jobhistory.move.interval-ms=1000,core:fs.gs.parent.timestamp.update.substrings.includes=gs://gcs-log-bucket /history,yarn:yarn.log-aggregation-enable=true,yarn:yarn.nodemanager.remote-app-log-dir=gs://gcs-log-bucket /logs/735ddd54-4920-46aa-9346-cbdea128ac83,yarn:yarn.log-aggregation.retain-seconds=-1,core:fs.gs.implicit.directory.repair=false
ERROR: (gcloud.dataproc.clusters.create) PERMISSION_DENIED: Not allowed to get project settings for project gc-spydra-test
 INFO [main] (LoggingMetrics.java:35) - Cluster was created with success=false and zoneUri=null
ERROR [main] (DynamicSubmitter.java:128) - Failed to create cluster
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at com.spotify.spydra.api.gcloud.GcloudExecutor.createCluster(GcloudExecutor.java:71)
	at com.spotify.spydra.api.DataprocAPI.createCluster(DataprocAPI.java:61)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.createNewCluster(DynamicSubmitter.java:162)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.acquireCluster(DynamicSubmitter.java:147)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.executeJob(DynamicSubmitter.java:122)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
 INFO [main] (LoggingMetrics.java:55) - Fatal error was caughtnull
DEBUG [main] (ProcessHelper.java:33) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com dataproc clusters delete spydra-19ebe301-f34e-4026-8aec-939f069265bd --async --quiet --region=ASIA-EAST1 --project=gc-spydra-test
ERROR: (gcloud.dataproc.clusters.delete) PERMISSION_DENIED: Not allowed to get project settings for project gc-spydra-test
 INFO [main] (LoggingMetrics.java:40) - Cluster was deleted with success=false
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.026 sec <<< FAILURE! - in com.spotify.spydra.LifecycleIT
testLifecycle(com.spotify.spydra.LifecycleIT)  Time elapsed: 4.866 sec  <<< FAILURE!
java.lang.AssertionError: job wasn't successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:85)


Results :

Failed tests: 
  LifecycleIT.testLifecycle:85 job wasn't successful

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.16:verify (default) @ spydra ---
[INFO] Failsafe report directory: /Users/kwangin/workspace/github_source/spydra/spydra/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spotify Spydra Parent .............................. SUCCESS [  1.287 s]
[INFO] common ............................................. SUCCESS [  4.874 s]
[INFO] metrics ............................................ SUCCESS [  1.345 s]
[INFO] api ................................................ SUCCESS [  1.855 s]
[INFO] spydra ............................................. FAILURE [ 22.733 s]
```
Could you find out something?

**Comment by krisss85** [comment]
Can you grant your service account spydra-test@gc-spydra-test.iam.gserviceaccount.com project editor role in IAM?

**Comment by djKooks** [comment]
@krisss85 Thanks for help! It seems almost close to solve.
I add account as you told, and pass issue above. But it shows something other.

```
DEBUG [main] (ProcessHelper.java:33) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com dataproc clusters delete spydra-b2003171-5be3-486f-88b1-59b525a237ee --async --quiet --region=ASIA-EAST1 --project=gc-spydra-test
ERROR: (gcloud.dataproc.clusters.delete) INVALID_ARGUMENT: Region 'ASIA-EAST1' invalid or not supported by this endpoint; permitted regions: '[global]'
 INFO [main] (LoggingMetrics.java:40) - Cluster was deleted with success=false
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.85 sec <<< FAILURE! - in com.spotify.spydra.LifecycleIT
testLifecycle(com.spotify.spydra.LifecycleIT)  Time elapsed: 2.682 sec  <<< FAILURE!
java.lang.AssertionError: job wasn't successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:85)

Results :

Failed tests: 
  LifecycleIT.testLifecycle:85 job wasn't successful
```

This is my integration json file.
```
{
  "log_bucket": "gcs-log-bucket ",
  "region": "ASIA-EAST1"
}
```

I tried region as 'global' and 'europe-west1-d' but it all failed. What do I have to put on?

**Comment by varjoranta** [comment]
”europe-west1” is a region. ”europe-west1-d” is a zone.

**Comment by djKooks** [comment]
@varjoranta Thanks!
But using 'europe-west1' causes other bug.

```
DEBUG [main] (ProcessHelper.java:50) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com --format=json dataproc clusters create spydra-dd6231ab-52b0-4d60-b310-ff313b84f0db --quiet --metadata=heartbeat=2017-11-09T07:31:21.045000Z,collector-timeout=30 --project=gc-spydra-test --scopes=cloud-platform --num-workers=3 --region=europe-west1 --service-account=spydra-test@gc-spydra-test.iam.gserviceaccount.com --properties=mapred:mapreduce.jobhistory.done-dir=gs://gcs-log-bucket /history/9202059e-bb07-4888-971c-188a468078b9/done,mapred:mapreduce.jobhistory.intermediate-done-dir=gs://gcs-log-bucket /history/9202059e-bb07-4888-971c-188a468078b9/4a92e6f7-291a-4da3-a63b-b869c689f72e/done_intermediate,mapred:mapreduce.jobhistory.move.interval-ms=1000,core:fs.gs.parent.timestamp.update.substrings.includes=gs://gcs-log-bucket /history,yarn:yarn.log-aggregation-enable=true,yarn:yarn.nodemanager.remote-app-log-dir=gs://gcs-log-bucket /logs/9202059e-bb07-4888-971c-188a468078b9,yarn:yarn.log-aggregation.retain-seconds=-1,core:fs.gs.implicit.directory.repair=false
ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Multiple validation errors:
 - Insufficient 'CPUS' quota. Requested 16.0, available 8.0.
 - This request exceeds CPU quota. Some things to try: request fewer workers (a minimum of 2 is required), use smaller master and/or worker machine types (such as n1-standard-2).
 INFO [main] (LoggingMetrics.java:35) - Cluster was created with success=false and zoneUri=null
ERROR [main] (DynamicSubmitter.java:128) - Failed to create cluster
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at com.spotify.spydra.api.gcloud.GcloudExecutor.createCluster(GcloudExecutor.java:71)
	at com.spotify.spydra.api.DataprocAPI.createCluster(DataprocAPI.java:61)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.createNewCluster(DynamicSubmitter.java:162)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.acquireCluster(DynamicSubmitter.java:147)
	at com.spotify.spydra.submitter.api.DynamicSubmitter.executeJob(DynamicSubmitter.java:122)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
 INFO [main] (LoggingMetrics.java:55) - Fatal error was caughtnull
DEBUG [main] (ProcessHelper.java:33) - Executing command: gcloud --account spydra-test@gc-spydra-test.iam.gserviceaccount.com dataproc clusters delete spydra-dd6231ab-52b0-4d60-b310-ff313b84f0db --async --quiet --region=europe-west1 --project=gc-spydra-test
ERROR: (gcloud.dataproc.clusters.delete) NOT_FOUND: No current cluster for project id 'gc-spydra-test' with name 'spydra-dd6231ab-52b0-4d60-b310-ff313b84f0db'
 INFO [main] (LoggingMetrics.java:40) - Cluster was deleted with success=false
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.805 sec <<< FAILURE! - in com.spotify.spydra.LifecycleIT
testLifecycle(com.spotify.spydra.LifecycleIT)  Time elapsed: 8.631 sec  <<< FAILURE!
java.lang.AssertionError: job wasn't successful
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.spotify.spydra.LifecycleIT.testLifecycle(LifecycleIT.java:85)


Results :

Failed tests: 
  LifecycleIT.testLifecycle:85 job wasn't successful

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
What do I have to look on? Also, can I use asia region here?

**Comment by krisss85** [comment]
Look at the stack trace:

Insufficient 'CPUS' quota. Requested 16.0, available 8.0.
 - This request exceeds CPU quota. Some things to try: request fewer workers (a minimum of 2 is required), use smaller master and/or worker machine types (such as n1-standard-2).

Maybe you should try specifying your asia region with lowercase?

**Comment by djKooks** [comment]
@krisss85 @varjoranta @steffengr It works well now! Thanks for your help during long time.
Now I'll really 'close' this one.

**Comment by krisss85** [comment]
Enjoy spydra then. Happy hacking.

**Comment by djKooks** [comment]
@krisss85 Thanks!
Just a simple question...Is there some simple way to check cluster is running well, or example using cluster?

**Comment by krisss85** [comment]
If you are looking for hadoop UIs you are familiar with you can check https://github.com/spotify/dataprocxy
Then you will be able to access RM UI with more details on the currently running jobs.

Whether the job already finished and cluster is gone. JHS is your friend.
https://github.com/spotify/spydra#running-an-embedded-jobhistoryserver

**Comment by djKooks** [comment]
@krisss85 Thanks for guide!
